apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sss
spec:
  serviceName: postgres
  replicas: 2
  selector:
    matchLabels:
      app: stateful-postgres
  template:
    metadata:
      labels:
        app: stateful-postgres
    spec:
      shareProcessNamespace: true
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: pvc-volume
            mountPath: /var/lib/postgresql/data
          envFrom:
          - configMapRef:
              name: postgres-config
        - name: sss
          image: expresscluster/sss4postgres:4.1.2-1
          command: ['/usr/local/bin/docker-entrypoint.sh']
          volumeMounts:
            - name: config
              mountPath: /opt/nec/clusterpro/etc/sss4postgres.conf
              subPath: sss4postgres.conf
      volumes:
        - name: config
          configMap:
            name: sss4postgres
  volumeClaimTemplates:
  - metadata:
      name: pvc-volume
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi

